apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-dummy-server
  labels:
    app: express-dummy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-dummy-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: express-dummy-server
    spec:
      containers:
        - name: express-dummy-server
          image: NULL
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
