apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-dummy-server
  name: express-dummy-server
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: express-dummy-server
  sessionAffinity: None
